name: DhanyIrfan
favicon: null
layout_spectrum: 0
typography_spectrum: 0.5504833
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Dhany Irfan
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.7772732
  lightness: 0.5526316
  saturation: 0.2132116
  rhythmicContrast: 0.2851772
purpose: []
