layout_spectrum: 0.3764769
typography_spectrum: 0.5504833
color:
  saturation: 0.5417188
  lightness: 0.8293306
  brandStrength: 0.7772732
  rhythmicContrast: 0.7223108
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
name: DhanyIrfan
