name: DhanyIrfan
favicon: null
layout_spectrum: 0
typography_spectrum: 0.55974
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Dhany Irfan
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b6b6b6'
    - '#dd4833'
    - '#109d56'
    - '#424242'
  brandStrength: 0.75
  lightness: 0.5526316
  saturation: 0.5
  rhythmicContrast: 0.2851772
purpose: []
